name: 'Dependency Review'
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        id: review
        uses: check-spelling-sandbox/dependency-review-action@main
        with:
          base-ref: ${{ github.pull_request.base.sha || env.base_ref_1 }}
          head-ref: ${{ github.pull_request.head.sha || github.head_ref }}
        env:
          base_ref_1: "${{ github.head_ref }}~"
      - name: 'Report'
        shell: bash
        env:
          comment: ${{ steps.review.outputs.comment-content }}
        run: |
          echo "$comment"
